version: "3"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app_sistemsb:
    build: .
    volumes:
      - static:/code/sistema/staticfiles
      - media:/code/sistema/media
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.13
    ports:
      - "7500:8080"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/sistema/staticfiles
      - media:/code/sistema/media
    depends_on:
      - django_app_sistemsb

volumes:
  .:
  postgres_data:
  static:
  media:



